name: 运行 plugin_repackaging.sh 脚本

# 触发方式：支持手动触发（可输入参数）
on:
  workflow_dispatch:
    inputs:
      author:
        description: 'plugin author'
        required: true
        default: ''
        type: string
      name:
        description: 'plugin name'
        required: true
        default: ''
        type: string
      version:
        description: 'plugin version'
        required: true
        default: ''
        type: string

# 任务：拉代码 → 执行脚本
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 给脚本加执行权限
        run: chmod +x ./plugin_repackaging.sh

      - name: 运行脚本并传入参数 [plugin author] [plugin name] [plugin version]
        run: ./plugin_repackaging.sh market "${{ inputs.author }}" "${{ inputs.name }}" "${{ inputs.version }}"
